### * Recuperar todas las peliculas
GET http://localhost:1234/movies

### * Recuperar todas las peliculas por género
GET http://localhost:1234/movies?genre=Action

### * Recuperar una película por ID
GET http://localhost:1234/movies/04986507-b3ed-442c-8ae7-4c5df804f896

### * Crear una pelicula 
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Prueba",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime", 
    "Drama"
    ],
    "rate": 8.3
}

### * Borrar una pelicula
DELETE http://localhost:1234/movies/04986507-b3ed-442c-8ae7-4c5df804f896


### * Actualizar una película
PATCH http://localhost:1234/movies/04986507-b3ed-442c-8ae7-4c5df804f896
Content-Type: application/json

{
  "year": 2012
}